### ISSUE TITLE
Ask for datasets help

### ISSUE THREAD

**Issue by yqw0710** [princeton-nlp/MABEL#2]
Hi,I read your article and found that the experimental results were very effective. I learned that your training datasets came from MNLI and SNLI, but I didn't find what sensitive attributes you referred to, and i didn't know the specific preprocessing steps. Could you please provide the processed data or preprocessed code?Thank you very much!

**Comment by aditya-anulekh** [comment]
Hey!
Did you manage to find the preprocessing steps for generating the dataset? If so, could you please point me to them?
Thanks!

**Comment by jacqueline-he** [comment]
The dataset (as linked in the README) can be found [here](https://drive.google.com/file/d/16KPp0rZv2DqAumccaRgvpLW4NwRCfdl6/view?usp=sharing).

I have since graduated and no longer have access to the original preprocessing script, but I'd imagine that recreating it should be pretty simple. You can download the SNLI or MNLI dataset from HuggingFace, and filter for the entailment pairs (so the premise and hypothesis would be **orig_sent0** and **orig_sent1**, respectively). Then, apply CDA using the 10 or so gender word pairs listed in Appendix A of the paper - the gender-flipped premise and hypothesis would then be **aug_sent0** and **aug_sent1**, respectively. Finally, the column for **both** is 1 if both the premise and the hypothesis have gendered words that are flipped, and 0 otherwise (this affects the computation of one of the losses).  

Let me know if you have any other questions.
