### ISSUE TITLE
Using crows pairs multiple times will result in different measurements

### ISSUE THREAD

**Issue by struggle12** [princeton-nlp/MABEL#6]
hi,
I ran into a problem with multiple crows-pairs metrics with different results. After training the model using bert-base-cased/ save locally, I used crows pairs multiple times to measure different results. Figure:
![image](https://github.com/princeton-nlp/MABEL/assets/53340136/851f7d40-d23a-4a56-b86e-3e853ce7ded2)

Thank you very much for answering my questions and solving them, which is very helpful for my research.

**Comment by jacqueline-he** [comment]
Hi,

I'm not sure I fully understand your question—are you saying that you are getting high variance in CrowS-Pairs results from using `bert-base-cased` instead of `bert-base-uncased`? I've only ever tried training with uncased models, as I don't think casing particularly matters for any of the tasks at hand (either upstream or downstream). 

From your attached screenshot, the numbers look reasonable (a deviation of 3.82 from 50—the ideal score), but for a sanity check you could compare them against `bert-base-cased` without any further training. Even in the cased setting, I would expect MABEL to have a better CrowS-Pairs score than BERT. 

CrowS-Pairs is also a relatively small dataset (only 266 examples), so I would expect some variance across training runs. But if you are loading an already trained checkpoint and just running the metric multiple times, then the numbers should not change.

**Comment by struggle12** [comment]
My problem was loading a trained checkpoint and ust running the metric multiple times,with different results each time.I don't know what the reason is, but the same thing happens with other metrics.

All training steps are not different from the commands provided.

**Comment by struggle12** [comment]
hi,

My problem was loading a trained checkpoint and ust running the metric multiple times,with different results each time.I don't know what the reason is, but the same thing happens with other metrics.

All training steps are not different from the commands provided.

**Comment by jacqueline-he** [comment]
I'm not sure why you're running into this issue--I just tried re-running CrowS-Pairs locally with a saved checkpoint, and the results were fixed. To debug, I'd recommend the following:

- Try cloning a fresh copy of the repository and running `python -m benchmark.intrinsic.crows.eval --model_name_or_path princeton-nlp/mabel-bert-base-uncased`. The numbers should exactly match what was reported in `README.md`, since we are downloading and loading from a frozen checkpoint. 
- If the numbers do match exactly, try replacing `princeton-nlp/mabel-bert-base-uncased` with the local path to your trained model (and also make sure that you are using a compatible tokenizer). 

Do you also get varying results from the same trained checkpoint on StereoSet?

**Comment by struggle12** [comment]
I use your trained princeton-nlp/ mable-bert-base-uncased without this issue. This is a problem when I retrain using your code. Using stereosets has the same problem.
Is it because the argument wasn't saved where I highlighted it in red?
![image](https://github.com/princeton-nlp/MABEL/assets/53340136/60c2f35d-623f-405b-ba15-b302cc088141)
I'm not sure which part of the training was wrong.

**Comment by jacqueline-he** [comment]
Did you convert the trained model checkpoint to its HF checkpoint prior to intrinsic evaluation? From the README:


> If you use your own trained model instead of our provided HF checkpoint, you must first run python -m training.convert_to_hf --path /path/to/your/checkpoint --base_model bert (which converts the checkpoint to a standard BertForMaskedLM model - use --base_model roberta for RobertaForMaskedLM) prior to intrinsic evaluation

I tried a training run locally, and converted the checkpoint before running CrowS-Pairs. I did not get the message boxed in red.

**Comment by struggle12** [comment]
After I ran python -m training.convert_to_hf --path /path/to/your/checkpoint --base_model bert, the problem was solved.

Thank you very much for your patience to help me solve this problem.

**Comment by jacqueline-he** [comment]
That's great! Glad it worked out.

I'm closing this issue for now, but feel free to re-open or start a new thread if you run into additional issues.
